{
    "name": "UI and Template Enhancements",
    "summary": "Cleans up default branding, enhances reports and email templates.",
    "version": "16.0.1.0.2",
    "category": "Tools",
    "author": "Antonio Caballero",
    "license": "AGPL-3",
    "website": "https://github.com/zurbaran/odoo_metal_manufacturing",
    "depends": [
        "base",
        "web",
        "portal",
        "digest",
        "auth_signup",
        "mail",
        "hr_expense",
    ],
    "data": [
        "views/login_layout.xml",
        "views/login.xml",
        "views/mail_notification_light.xml",
        "views/mail_notification_layout.xml",
        "views/portal_record_sidebar.xml",
        "views/reset_password_email.xml",
        "views/alert_login_new_device.xml",
        "views/digest_mail_main.xml",
        "views/digest_section_mobile.xml",
        "views/brand_promotion_message.xml",
        "views/hr_expense_template_register_no_user.xml",
        "views/sale_order_report_custom.xml",
        "views/invoice_report_custom.xml",
    ],
    "installable": True,
    "application": False,
}
